Add files via upload
zemoso-int/anjaligupta_ldp pull request #1
Opened 2022-07-08 10:53 UTC by AnjaliGupta-Zemoso

Assignments for JavaScript module

2022-07-08 11:18 UTC, rakeshreddym21 requested changes

2022-07-08 11:18 UTC, rakeshreddym21 commented on storageAssignment_scripts.js
> +    localStorage.setItem("local",i);
Check the logic of local score function,on tab close it will be set to 0.That shouldn't be the case of local storage.

2022-07-13 12:21 UTC, AnjaliGupta-Zemoso commented on storageAssignment_scripts.js
> +    localStorage.setItem("local",i);
I have rectified that and committed the new changes.

2022-07-13 12:29 UTC, rakeshreddym21 approved these changes

2022-07-13 12:50 UTC, merged